# ... (parte del archivo YAML existente)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar Dependencias
        run: |
          cd jsgaston.github.io
          npm install -g npm@latest
          npm install -g yarn
          npm install
          
      - name: Generar JSON
        run: |
          cd jsgaston.github.io
          node generate_json.js

      - name: Commit y Push Cambios
        run: |
          cd jsgaston.github.io
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add music_list.json
          git commit -m "Actualizar lista de canciones [skip ci]"
          git push
