name: Actualizar Lista de Canciones

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r jsgaston.github.io/requirements.txt  # Si tienes un archivo requirements.txt con las dependencias

      - name: Generar JSON
        run: |
          cd jsgaston.github.io
          python generate_json.py

      - name: Commit y Push Cambios
        run: |
          cd jsgaston.github.io
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add music_list.json
          git commit -m "Actualizar lista de canciones [skip ci]"
          git push

